name: codejet_cli
description: A simplified & clean Flutter file structure framework based on Bloc pattern.
version: 1.0.2
repository: https://github.com/codejet-dev-official/CodeJet-CLI.git

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  process_run: ^0.13.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  codejet: codejet